DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.0, 0.0, 0.0]   # [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [1.0, 1.0, 1.0]    # [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0035
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20
  CHECKPOINT_FREQ: 10

MODEL:
  BACKBONE:
    NAME: "ViT-B/32"

TRAINER:
  MoEAdvMaPLe:
    N_CTX: 2
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH: 9
    NUM_EXPERTS: 3

AT:
  TRAIN:
    EPS: 1
    ALPHA: 1
    STEPS: 2
    AT_LOSS_TYPE: "adv_half"

  TEST:
    EPS: 1
    ALPHA: 1
    STEPS: 100